-- Telegram account linking
-- Links a Telegram user to a StackAI user via a short-lived one-time code,
-- generated by the bot (/link) and consumed on the web (/link?code=...).

-- Each StackAI user can link one Telegram account.
alter table users add column if not exists telegram_id text unique;

-- Pending link codes. The bot inserts a code tied to a telegram_id; the web
-- /link page (after X sign-in) reads it, sets users.telegram_id, and deletes it.
create table if not exists telegram_link_codes (
  code              text primary key,
  telegram_id       text not null,
  telegram_username text,
  created_at        timestamptz not null default now()
);

-- Accessed only by the service role (bot + web server actions). Enable RLS with
-- no policies so the anon/auth keys can't touch it; the service key bypasses RLS.
alter table telegram_link_codes enable row level security;
