import Link from "next/link";

export const metadata = {
  title: "Terms of Service",
  description: "The terms for using StackAI.",
};

const UPDATED = "June 7, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="mb-2 text-lg font-semibold text-white">{title}</h2>
      <div className="space-y-3 text-[15px] leading-relaxed text-[#aaa]">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen max-w-2xl px-6 py-14">
      <Link
        href="/"
        className="font-mono text-xs uppercase tracking-wider text-[#888] hover:text-white"
      >
        ← Stack<span className="text-[#e8ff47]">AI</span>
      </Link>

      <h1 className="mt-8 text-3xl font-bold text-white">Terms of Service</h1>
      <p className="mt-2 text-sm text-[#666]">Last updated: {UPDATED}</p>

      <Section title="1. Acceptance">
        <p>
          By using StackAI (the &ldquo;Service&rdquo;) — including the CLI, web
          app, and editor extension — you agree to these Terms. If you don&apos;t
          agree, don&apos;t use the Service.
        </p>
      </Section>

      <Section title="2. The Service">
        <p>
          StackAI is an AI coding agent that can read, write, and edit files and
          run commands you approve. Output is generated by an AI model and may be
          inaccurate or incomplete. <strong className="text-white">You are
          responsible for reviewing and testing any code or commands before
          relying on them.</strong>
        </p>
      </Section>

      <Section title="3. Accounts &amp; API keys">
        <p>
          You sign in with X (Twitter). Keep your API keys secret — you are
          responsible for all activity under your keys. If a key is exposed,
          revoke it from your dashboard.
        </p>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>use the Service for anything illegal or harmful;</li>
          <li>
            attempt to bypass rate limits, abuse the infrastructure, or disrupt
            the Service;
          </li>
          <li>
            reverse engineer, resell, or misrepresent the Service; or
          </li>
          <li>use it to generate malware or content that violates others&apos; rights.</li>
        </ul>
      </Section>

      <Section title="5. Rate limits &amp; tiers">
        <p>
          Usage is subject to per-key daily limits based on your tier. We may
          adjust limits and tiers over time.
        </p>
      </Section>

      <Section title="6. No warranty">
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranties of any
          kind. We don&apos;t guarantee the Service will be uninterrupted,
          error-free, or that AI output will be correct.
        </p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>
          To the maximum extent permitted by law, StackAI is not liable for any
          indirect, incidental, or consequential damages, or for any loss
          arising from your use of the Service or reliance on its output.
        </p>
      </Section>

      <Section title="8. Changes &amp; termination">
        <p>
          We may update these Terms or the Service at any time. We may suspend or
          terminate access that violates these Terms. Continued use after changes
          means you accept the updated Terms.
        </p>
      </Section>

      <Section title="9. Contact">
        <p>
          Questions? Reach us at{" "}
          <a
            href="mailto:hello@usestackai.com"
            className="text-[#e8ff47] underline"
          >
            hello@usestackai.com
          </a>{" "}
          or{" "}
          <a
            href="https://x.com/askstackai"
            className="text-[#e8ff47] underline"
          >
            @askstackai
          </a>
          .
        </p>
      </Section>
    </main>
  );
}
